import type { Metadata } from "next";
import { inter } from "@/components/ui/fonts";
import "@/components/ui/globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex flex-col ${inter.className}`}>
        <Header />
        <div className="flex flex-row mt-14">
          <Sidebar />
          <div className="flex-grow p-4 md:overflow-y-auto ml-[250px]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
